# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/slurm_ops',
                'doc_host': 'https://DeanLight.github.io',
                'git_url': 'https://github.com/DeanLight/slurm_ops',
                'lib_path': 'slurm_ops'},
  'syms': { 'slurm_ops.core': { 'slurm_ops.core.find_free_port': ('core.html#find_free_port', 'slurm_ops/core.py'),
                                'slurm_ops.core.start_or_connect': ('core.html#start_or_connect', 'slurm_ops/core.py')}}}
