"""Agent module: understand a Lean project, ask vLLM, splice, lake build.

Provides:
  - `inspect_project(project_root)` — lightweight Lake/Lean project summary.
  - `load_project_instructions(project_root)` — repo-local agent guidance.
  - `find_sorrys(project_root)` — LSP-driven: list every sorry with decl name + context.
  - `ask_for_proof(decl, sig, ctx)` — ask vLLM for a replacement declaration.
  - `ask_project_question(question)` — ask vLLM about the project context.
  - `run_loop(project_root)` — REPL: chat/context/list/show/ask/try/build/quit.
  - `main()` — entrypoint for `agent/bin/gcd-agent`; loads .env, instantiates the REPL.

Reads `LEAN_REPO_PATH` from env or from `.env` next to the agent dir. vLLM
endpoint is `OPENAI_BASE_URL`/`OPENAI_API_KEY`/`VLLM_MODEL` (set by `vllm-up`).
"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_agent.ipynb.

# %% auto 0
__all__ = [
    "LeanProjectContext", "SorryHit", "Attempt", "Proposal",
    "load_env_file", "load_project_instructions", "inspect_project",
    "render_project_context", "find_sorrys", "ask_for_proof",
    "ask_project_question",
    "splice", "lake_build", "AgentShell", "run_loop", "main",
]

# %% ../nbs/03_agent.ipynb 4
import argparse
import cmd
import dataclasses
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import tomllib
import urllib.error
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional


# ---------------------------------------------------------------------------
#  .env loader (no python-dotenv dep)
# ---------------------------------------------------------------------------

def load_env_file(path: Path) -> dict[str, str]:
    """Parse KEY=value lines from `path`, setdefault into os.environ, return dict.

    Empty lines and lines beginning with `#` are ignored. Surrounding quotes
    are stripped. Existing env vars are NOT overwritten — explicit shell
    exports win.
    """
    out: dict[str, str] = {}
    if not path.is_file():
        return out
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, val = line.split("=", 1)
        key = key.strip()
        val = val.strip()
        if (val.startswith('"') and val.endswith('"')) or (val.startswith("'") and val.endswith("'")):
            val = val[1:-1]
        out[key] = val
        os.environ.setdefault(key, val)
    return out


# ---------------------------------------------------------------------------
#  Lean project context
# ---------------------------------------------------------------------------

DEFAULT_INSTRUCTION_FILES = (
    ".gcd/agent.md",
    ".gcd/context.md",
    ".gcd/instructions.md",
    "AGENTS.md",
)

DEFAULT_BASE_URL = "http://localhost:8000/v1"
DEFAULT_API_KEY = "dummy"
DEFAULT_MODEL = "Qwen/Qwen3-8B"


@dataclass
class LeanProjectContext:
    """Compact, reusable context about the Lean project under automation."""

    root: str
    lakefile: Optional[str]
    package_name: Optional[str]
    toolchain: Optional[str]
    dependencies: list[str]
    source_roots: list[str]
    lean_file_count: int
    sorry_like_count: int
    git_branch: Optional[str]
    git_status: list[str]
    readme_excerpt: str
    instruction_files: list[str]
    instructions: str

    def as_dict(self) -> dict[str, Any]:
        return dataclasses.asdict(self)


def _read_text_limited(path: Path, *, max_chars: int = 4000) -> str:
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        return ""
    if len(text) > max_chars:
        return text[:max_chars].rstrip() + "\n..."
    return text.strip()


def _run_quiet(cmd: list[str], cwd: Path) -> Optional[str]:
    try:
        r = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=5)
    except (OSError, subprocess.TimeoutExpired):
        return None
    if r.returncode != 0:
        return None
    return r.stdout.strip()


def _detect_lakefile(root: Path) -> Optional[Path]:
    for name in ("lakefile.lean", "lakefile.toml"):
        path = root / name
        if path.is_file():
            return path
    return None


def _parse_lakefile_lean(path: Path) -> tuple[Optional[str], list[str]]:
    text = _read_text_limited(path, max_chars=20000)
    package_name = None
    deps: list[str] = []

    m = re.search(r"^\s*package\s+([A-Za-z0-9_'.-]+)", text, re.MULTILINE)
    if m:
        package_name = m.group(1).strip('"')

    for m in re.finditer(r"^\s*require\s+([A-Za-z0-9_'.-]+)", text, re.MULTILINE):
        dep = m.group(1).strip('"')
        if dep not in deps:
            deps.append(dep)
    return package_name, deps


def _parse_lakefile_toml(path: Path) -> tuple[Optional[str], list[str]]:
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError):
        return None, []

    package = data.get("package", {})
    package_name = package.get("name") if isinstance(package, dict) else None
    deps: list[str] = []
    raw_deps = data.get("require") or data.get("dependencies") or []
    if isinstance(raw_deps, list):
        for item in raw_deps:
            if isinstance(item, dict) and isinstance(item.get("name"), str):
                deps.append(item["name"])
            elif isinstance(item, str):
                deps.append(item)
    elif isinstance(raw_deps, dict):
        deps.extend(str(k) for k in raw_deps)
    return package_name, deps


def _detect_package(root: Path, lakefile: Optional[Path]) -> tuple[Optional[str], list[str]]:
    if lakefile is None:
        return None, []
    if lakefile.name == "lakefile.toml":
        return _parse_lakefile_toml(lakefile)
    return _parse_lakefile_lean(lakefile)


def _lean_files(root: Path) -> list[Path]:
    skip = {".lake", "lake-packages", ".git"}
    return sorted(
        p for p in root.rglob("*.lean")
        if not any(part in skip for part in p.parts)
        and p.name != "lakefile.lean"
    )


def _detect_source_roots(root: Path, files: list[Path]) -> list[str]:
    roots: set[str] = set()
    for path in files:
        try:
            rel = path.relative_to(root)
        except ValueError:
            continue
        if rel.name == "lakefile.lean":
            continue
        roots.add(rel.parts[0] if len(rel.parts) > 1 else ".")
    return sorted(roots)


def _count_sorry_like(files: list[Path]) -> int:
    count = 0
    for path in files:
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        count += len(re.findall(r"\b(sorry|admit)\b", text))
    return count


def load_project_instructions(
    project_root: Path,
    explicit_path: Optional[Path] = None,
) -> tuple[str, list[str]]:
    """Load project-specific guidance for the agent.

    Default files are intentionally explicit and small: `.gcd/agent.md`,
    `.gcd/context.md`, `.gcd/instructions.md`, and `AGENTS.md`. The first
    existing files are concatenated and included in every vLLM request.
    """
    root = Path(project_root).expanduser().resolve()
    paths: list[Path]
    if explicit_path is not None:
        p = explicit_path.expanduser()
        paths = [p if p.is_absolute() else root / p]
    else:
        paths = [root / name for name in DEFAULT_INSTRUCTION_FILES]

    chunks: list[str] = []
    used: list[str] = []
    for path in paths:
        if not path.is_file():
            continue
        text = _read_text_limited(path, max_chars=8000)
        if not text:
            continue
        used.append(str(path))
        chunks.append(f"# {path.name}\n{text}")
    return "\n\n".join(chunks).strip(), used


def inspect_project(
    project_root: Path,
    *,
    instructions_path: Optional[Path] = None,
) -> LeanProjectContext:
    """Return a compact Lean project summary suitable for model prompts."""
    root = Path(project_root).expanduser().resolve()
    lakefile = _detect_lakefile(root)
    package_name, dependencies = _detect_package(root, lakefile)
    files = _lean_files(root)

    toolchain = None
    toolchain_path = root / "lean-toolchain"
    if toolchain_path.is_file():
        toolchain = _read_text_limited(toolchain_path, max_chars=200).strip() or None

    git_branch = _run_quiet(["git", "branch", "--show-current"], root)
    status_text = _run_quiet(["git", "status", "--short"], root) or ""
    git_status = [line for line in status_text.splitlines() if line]
    instructions, instruction_files = load_project_instructions(root, instructions_path)

    return LeanProjectContext(
        root=str(root),
        lakefile=lakefile.name if lakefile else None,
        package_name=package_name,
        toolchain=toolchain,
        dependencies=dependencies,
        source_roots=_detect_source_roots(root, files),
        lean_file_count=len(files),
        sorry_like_count=_count_sorry_like(files),
        git_branch=git_branch or None,
        git_status=git_status[:30],
        readme_excerpt=_read_text_limited(root / "README.md", max_chars=2500),
        instruction_files=instruction_files,
        instructions=instructions,
    )


def render_project_context(
    ctx: LeanProjectContext,
    *,
    extra_instructions: str = "",
    include_readme: bool = True,
) -> str:
    """Render `LeanProjectContext` as a compact prompt section."""
    lines = [
        "Lean project context:",
        f"- root: {ctx.root}",
        f"- lakefile: {ctx.lakefile or '(none)'}",
        f"- package: {ctx.package_name or '(unknown)'}",
        f"- toolchain: {ctx.toolchain or '(unknown)'}",
        f"- dependencies: {', '.join(ctx.dependencies) if ctx.dependencies else '(none detected)'}",
        f"- source roots: {', '.join(ctx.source_roots) if ctx.source_roots else '(none detected)'}",
        f"- Lean files: {ctx.lean_file_count}",
        f"- sorry/admit count: {ctx.sorry_like_count}",
        f"- git branch: {ctx.git_branch or '(unknown)'}",
    ]
    if ctx.git_status:
        lines.append("- git status:")
        lines.extend(f"  {line}" for line in ctx.git_status[:15])
    else:
        lines.append("- git status: clean or unavailable")

    if ctx.instruction_files:
        lines.append("- instruction files:")
        lines.extend(f"  {path}" for path in ctx.instruction_files)

    sections = ["\n".join(lines)]
    if ctx.instructions:
        sections.append("Project instructions:\n" + ctx.instructions)
    if extra_instructions.strip():
        sections.append("Session instructions:\n" + extra_instructions.strip())
    if include_readme and ctx.readme_excerpt:
        sections.append("README excerpt:\n" + ctx.readme_excerpt)
    return "\n\n".join(sections).strip()


# ---------------------------------------------------------------------------
#  vLLM client (OpenAI-compatible, points at $OPENAI_BASE_URL)
# ---------------------------------------------------------------------------

@dataclass
class Proposal:
    raw: str
    proof: str
    model: str
    prompt_tokens: int
    completion_tokens: int


SYSTEM_PROMPT = """You are an assistant working inside a Lean 4 project.
Use the provided project context, user instructions, imports, local declarations,
and Lean diagnostics. Do not change theorem statements, definitions, imports, or
names unless the user explicitly asks. Reply with the exact full Lean
declaration that should replace the current declaration, inside a single
```lean ... ``` fenced block. No prose, no explanation, no `<think>` block.
The replacement must type-check; if you are uncertain, prefer leaving the proof
as `by sorry` over guesses that will not compile."""


def _post_json(url: str, payload: dict, *, api_key: str = "dummy", timeout_s: int = 120) -> dict:
    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(
        url,
        data=data,
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout_s) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"HTTP {e.code} from {url}: {body}") from e


def resolved_base_url() -> str:
    return os.environ.get("OPENAI_BASE_URL", DEFAULT_BASE_URL).rstrip("/")


def resolved_api_key() -> str:
    return os.environ.get("OPENAI_API_KEY", DEFAULT_API_KEY)


def resolved_model() -> str:
    return os.environ.get("VLLM_MODEL", DEFAULT_MODEL)


def _env_label(key: str, default: str) -> str:
    value = os.environ.get(key)
    return value if value else f"{default} (default)"


def _strip_think(text: str) -> str:
    """Remove Qwen3-style <think>...</think> reasoning blocks from a reply."""
    text = re.sub(r"<think>.*?</think>\s*", "", text, flags=re.DOTALL)
    text = re.sub(r"<think>.*", "", text, flags=re.DOTALL)
    return text.strip()


def _extract_lean_block(text: str) -> str:
    """Pull the body of the first ```lean ... ``` fence, else the whole text."""
    text = _strip_think(text)
    m = re.search(r"```(?:lean4?|lean)?\s*\n(.*?)```", text, re.DOTALL)
    return m.group(1).strip() if m else text.strip()


def ask_for_proof(
    decl_name: str,
    signature: str,
    surrounding_context: str,
    *,
    project_context: Optional[LeanProjectContext | str] = None,
    imports: str = "",
    diagnostic_message: str = "",
    extra_instructions: str = "",
    model: Optional[str] = None,
    max_tokens: int = 2048,
    temperature: float = 0.0,
    timeout_s: int = 120,
) -> Proposal:
    """Send a single sorry to vLLM and return the candidate replacement."""
    chosen = model or resolved_model()
    if isinstance(project_context, LeanProjectContext):
        project_block = render_project_context(
            project_context,
            extra_instructions=extra_instructions,
        )
    else:
        project_block = (project_context or "").strip()

    context_parts = []
    if project_block:
        context_parts.append(project_block)
    if imports.strip():
        context_parts.append(f"File imports:\n```lean\n{imports.strip()}\n```")
    if diagnostic_message.strip():
        context_parts.append(f"Lean diagnostic:\n{diagnostic_message.strip()}")
    context_parts.append(
        f"Declaration: {decl_name}\n\n"
        f"Signature:\n```lean\n{signature}\n```\n\n"
        f"Surrounding file context (the `sorry` is inside this declaration):\n"
        f"```lean\n{surrounding_context}\n```"
    )
    user = (
        "\n\n".join(context_parts)
        + "\n\nReplace the current declaration with a version that preserves "
        "the statement and fills the proof. Output only the full replacement "
        "declaration, inside one ```lean ... ``` block.\n\n/no_think"
    )
    base_url = resolved_base_url()
    api_key = resolved_api_key()
    payload = {
        "model": chosen,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user},
        ],
        "max_tokens": max_tokens,
        "temperature": temperature,
    }
    resp = _post_json(f"{base_url}/chat/completions", payload, api_key=api_key, timeout_s=timeout_s)
    msg = resp["choices"][0]["message"]["content"] or ""
    usage = resp.get("usage") or {}
    return Proposal(
        raw=msg,
        proof=_extract_lean_block(msg),
        model=chosen,
        prompt_tokens=int(usage.get("prompt_tokens") or 0),
        completion_tokens=int(usage.get("completion_tokens") or 0),
    )


def ask_project_question(
    question: str,
    *,
    project_context: LeanProjectContext,
    extra_instructions: str = "",
    model: Optional[str] = None,
    max_tokens: int = 1024,
    temperature: float = 0.0,
    timeout_s: int = 120,
) -> str:
    """Ask vLLM a free-form question about the Lean project context."""
    chosen = model or resolved_model()
    project_block = render_project_context(
        project_context,
        extra_instructions=extra_instructions,
    )
    user = (
        f"{project_block}\n\n"
        f"User question:\n{question.strip()}\n\n"
        "Answer using the project context. Be concrete and concise. If the user "
        "is asking how to operate this interface, call it the `gcd-agent` REPL. "
        "`list` shows sorry/admit proof targets, `show N` shows one target, "
        "`ask N` asks for a replacement declaration, and `try N` applies and "
        "build-checks the cached candidate.\n\n/no_think"
    )
    payload = {
        "model": chosen,
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are an assistant helping a user understand and work in "
                    "a Lean 4 project. Preserve theorem statements and imports "
                    "unless the user explicitly asks for changes."
                ),
            },
            {"role": "user", "content": user},
        ],
        "max_tokens": max_tokens,
        "temperature": temperature,
    }
    resp = _post_json(
        f"{resolved_base_url()}/chat/completions",
        payload,
        api_key=resolved_api_key(),
        timeout_s=timeout_s,
    )
    return _strip_think(resp["choices"][0]["message"]["content"] or "")


# ---------------------------------------------------------------------------
#  Lean LSP client + sorry finder
# ---------------------------------------------------------------------------

def _encode_lsp(msg: dict) -> bytes:
    body = json.dumps(msg).encode("utf-8")
    return f"Content-Length: {len(body)}\r\n\r\n".encode("ascii") + body


class _LeanLSP:
    """Minimal sync LSP client for `lake env lean --server`."""

    def __init__(self, project_root: Path) -> None:
        self.root = project_root.resolve()
        self.proc: Optional[subprocess.Popen] = None
        self._next_id = 1
        self._responses: dict[int, dict] = {}
        self._diagnostics: dict[str, list[dict]] = {}
        self._diag_seen: dict[str, threading.Event] = {}
        self._reader: Optional[threading.Thread] = None
        self._stop = threading.Event()

    def start(self) -> None:
        self.proc = subprocess.Popen(
            ["lake", "env", "lean", "--server"],
            cwd=self.root,
            stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            bufsize=0,
        )
        self._reader = threading.Thread(target=self._read_loop, daemon=True)
        self._reader.start()
        self._request("initialize", {
            "processId": os.getpid(),
            "rootUri": self.root.as_uri(),
            "capabilities": {
                "textDocument": {
                    "documentSymbol": {"hierarchicalDocumentSymbolSupport": True},
                    "publishDiagnostics": {},
                },
            },
        })
        self._notify("initialized", {})

    def stop(self) -> None:
        if self.proc and self.proc.poll() is None:
            try: self._notify("exit", {})
            except Exception: pass
            self.proc.terminate()
            try: self.proc.wait(timeout=3)
            except subprocess.TimeoutExpired: self.proc.kill()
        self._stop.set()

    def __enter__(self) -> "_LeanLSP":
        self.start(); return self
    def __exit__(self, *exc) -> None:
        self.stop()

    def _send(self, msg: dict) -> None:
        assert self.proc and self.proc.stdin
        self.proc.stdin.write(_encode_lsp(msg)); self.proc.stdin.flush()

    def _notify(self, method: str, params: Any) -> None:
        self._send({"jsonrpc": "2.0", "method": method, "params": params})

    def _request(self, method: str, params: Any, timeout: float = 60.0) -> Any:
        rid = self._next_id; self._next_id += 1
        self._send({"jsonrpc": "2.0", "id": rid, "method": method, "params": params})
        deadline = time.time() + timeout
        while time.time() < deadline:
            if rid in self._responses:
                resp = self._responses.pop(rid)
                if "error" in resp:
                    raise RuntimeError(f"LSP error on {method}: {resp['error']}")
                return resp.get("result")
            time.sleep(0.02)
        raise TimeoutError(f"LSP {method} timed out after {timeout}s")

    def _read_loop(self) -> None:
        assert self.proc and self.proc.stdout
        buf = b""
        try:
            while not self._stop.is_set():
                while b"\r\n\r\n" not in buf:
                    chunk = self.proc.stdout.read(4096)
                    if not chunk: return
                    buf += chunk
                header, _, rest = buf.partition(b"\r\n\r\n")
                clen = 0
                for line in header.split(b"\r\n"):
                    if line.lower().startswith(b"content-length:"):
                        clen = int(line.split(b":", 1)[1].strip())
                while len(rest) < clen:
                    chunk = self.proc.stdout.read(clen - len(rest))
                    if not chunk: return
                    rest += chunk
                body, buf = rest[:clen], rest[clen:]
                msg = json.loads(body.decode("utf-8"))
                self._handle(msg)
        except Exception:
            pass

    def _handle(self, msg: dict) -> None:
        if "id" in msg and ("result" in msg or "error" in msg):
            self._responses[msg["id"]] = msg
        elif msg.get("method") == "textDocument/publishDiagnostics":
            p = msg.get("params", {})
            uri = p.get("uri", "")
            self._diagnostics[uri] = p.get("diagnostics", [])
            ev = self._diag_seen.get(uri)
            if ev is not None: ev.set()

    def open_and_wait(self, path: Path, *, settle_seconds: float = 30.0) -> list[dict]:
        uri = path.as_uri()
        ev = threading.Event()
        self._diag_seen[uri] = ev
        text = path.read_text(encoding="utf-8")
        self._notify("textDocument/didOpen", {
            "textDocument": {"uri": uri, "languageId": "lean", "version": 1, "text": text},
        })
        if not ev.wait(timeout=settle_seconds):
            return self._diagnostics.get(uri, [])
        last_count = -1
        stable_since = time.time()
        while time.time() - stable_since < 3.0:
            cur = len(self._diagnostics.get(uri, []))
            if cur != last_count:
                last_count = cur; stable_since = time.time()
            time.sleep(0.5)
        return self._diagnostics.get(uri, [])

    def document_symbols(self, path: Path) -> list[dict]:
        return self._request("textDocument/documentSymbol", {
            "textDocument": {"uri": path.as_uri()},
        }) or []


@dataclass
class SorryHit:
    file: str
    line: int
    decl_name: str
    decl_range: tuple[int, int]
    imports: str
    signature: str
    surrounding: str
    diagnostic_message: str

    def as_dict(self) -> dict:
        d = dataclasses.asdict(self)
        d["decl_range"] = list(self.decl_range)
        return d


def _flatten_symbols(symbols: list[dict]) -> list[dict]:
    out: list[dict] = []
    def visit(s):
        out.append(s)
        for c in s.get("children", []) or []: visit(c)
    for s in symbols: visit(s)
    return out


def _enclosing_symbol(symbols_flat: list[dict], line: int) -> Optional[dict]:
    cands = []
    for s in symbols_flat:
        rng = s.get("range") or s.get("location", {}).get("range")
        if not rng: continue
        sl, el = rng["start"]["line"], rng["end"]["line"]
        if sl <= line <= el:
            cands.append((el - sl, s))
    if not cands: return None
    cands.sort(key=lambda x: x[0])
    return cands[0][1]


def _extract_signature(lines: list[str], start_line_0: int) -> str:
    out = []
    for i in range(start_line_0, min(len(lines), start_line_0 + 20)):
        out.append(lines[i])
        stripped = lines[i].strip()
        if ":= by" in stripped or stripped.endswith(":="):
            break
        if "sorry" in stripped:
            break
    return "\n".join(out)


def _extract_imports(lines: list[str]) -> str:
    imports = []
    for line in lines[:200]:
        stripped = line.strip()
        if stripped.startswith("import "):
            imports.append(line)
        elif stripped and not stripped.startswith("--") and imports:
            break
    return "\n".join(imports)


def _sorry_like_diagnostics(lines: list[str], existing: list[dict]) -> list[dict]:
    """Add text-search sorry/admit hits when Lean diagnostics are quiet."""
    seen_lines = {
        d.get("range", {}).get("start", {}).get("line")
        for d in existing
    }
    out = list(existing)
    for idx, line in enumerate(lines):
        if idx in seen_lines:
            continue
        if re.search(r"\b(sorry|admit)\b", line):
            out.append({
                "range": {"start": {"line": idx}, "end": {"line": idx}},
                "message": "syntactic sorry/admit placeholder",
            })
    return out


def _dedupe_hits(hits: list[SorryHit]) -> list[SorryHit]:
    by_decl: dict[tuple[str, str, tuple[int, int]], SorryHit] = {}
    for hit in hits:
        key = (hit.file, hit.decl_name, hit.decl_range)
        current = by_decl.get(key)
        if current is None:
            by_decl[key] = hit
            continue
        if current.diagnostic_message.startswith("syntactic ") and not hit.diagnostic_message.startswith("syntactic "):
            by_decl[key] = hit
    return list(by_decl.values())


def _hit_sort_key(hit: SorryHit) -> tuple[str, int, str]:
    return (hit.file, hit.decl_range[0], hit.decl_name)


def find_sorrys(project_root, files: Optional[list[str]] = None) -> list[SorryHit]:
    """List every `sorry` in `project_root` flagged by the Lean compiler."""
    root = Path(project_root).resolve()
    if files is None:
        targets = sorted(
            p for p in root.rglob("*.lean")
            if ".lake" not in p.parts and "lake-packages" not in p.parts
            and p.name != "lakefile.lean"
        )
    else:
        targets = [Path(f) if Path(f).is_absolute() else root / f for f in files]

    hits: list[SorryHit] = []
    with _LeanLSP(root) as lsp:
        for path in targets:
            text_lines = path.read_text(encoding="utf-8").splitlines()
            diags = lsp.open_and_wait(path)
            sorry_diags = [d for d in diags if "sorry" in (d.get("message") or "").lower()]
            sorry_diags = _sorry_like_diagnostics(text_lines, sorry_diags)
            if not sorry_diags:
                continue
            imports = _extract_imports(text_lines)
            symbols = _flatten_symbols(lsp.document_symbols(path))
            for d in sorry_diags:
                rng = d.get("range", {})
                start_line_0 = rng.get("start", {}).get("line", 0)
                sym = _enclosing_symbol(symbols, start_line_0)
                if sym:
                    sl = sym["range"]["start"]["line"]
                    el = sym["range"]["end"]["line"]
                    name = sym.get("name", "?")
                else:
                    sl = max(0, start_line_0 - 5)
                    el = min(len(text_lines) - 1, start_line_0 + 5)
                    name = "?"
                ctx_start = max(0, sl - 5)
                ctx_end = min(len(text_lines), el + 5)
                hits.append(SorryHit(
                    file=str(path),
                    line=start_line_0 + 1,
                    decl_name=name,
                    decl_range=(sl + 1, el + 1),
                    imports=imports,
                    signature=_extract_signature(text_lines, sl),
                    surrounding="\n".join(text_lines[ctx_start:ctx_end]),
                    diagnostic_message=d.get("message", ""),
                ))
    return sorted(_dedupe_hits(hits), key=_hit_sort_key)


# ---------------------------------------------------------------------------
#  Splice + build
# ---------------------------------------------------------------------------

@dataclass
class Attempt:
    file: str
    decl_name: str
    candidate: str
    accepted: bool
    build_stdout: str
    build_stderr: str


def _module_name_for(project_root: Path, lean_file: Path) -> Optional[str]:
    try:
        rel = lean_file.resolve().relative_to(project_root.resolve())
    except ValueError:
        return None
    if rel.suffix != ".lean": return None
    return ".".join(rel.with_suffix("").parts)


def splice(text: str, hit: SorryHit, replacement: str) -> str:
    """Substitute the entire enclosing declaration with `replacement`."""
    lines = text.splitlines(keepends=True)
    start, end = hit.decl_range[0] - 1, hit.decl_range[1] - 1
    head = "".join(lines[:start])
    tail = "".join(lines[end + 1:])
    middle = replacement.rstrip() + "\n"
    return head + middle + tail


def lake_build(project_root: Path, module: Optional[str] = None) -> tuple[int, str, str]:
    cmd = ["lake", "build"] + ([module] if module else [])
    r = subprocess.run(cmd, cwd=project_root, capture_output=True, text=True)
    return r.returncode, r.stdout, r.stderr


def _snapshot(path: Path) -> Path:
    tmp = Path(tempfile.mkdtemp(prefix="gcd-agent-")) / path.name
    shutil.copy2(path, tmp)
    return tmp


# ---------------------------------------------------------------------------
#  Slash-command REPL
# ---------------------------------------------------------------------------

class AgentShell(cmd.Cmd):
    """Interactive slash-command shell over the Lean project + vLLM."""

    intro = ""   # set in main()
    prompt = "gcd> "

    def __init__(
        self,
        project_root: Path,
        *,
        project_context: Optional[LeanProjectContext] = None,
        instructions_path: Optional[Path] = None,
        session_instructions: str = "",
    ) -> None:
        super().__init__()
        self.project_root = project_root
        self.instructions_path = instructions_path
        self.project_context = project_context or inspect_project(project_root)
        self.session_instructions = session_instructions.strip()
        self.hits: list[SorryHit] = []
        # last proposal per index (1-based), so `try N` knows what to apply.
        self.proposals: dict[int, Proposal] = {}

    # -- helpers -----------------------------------------------------------

    def _need_hits(self) -> bool:
        if not self.hits:
            print("(no sorry index loaded yet — run `list` first)")
            return True
        return False

    def _idx(self, arg: str) -> Optional[int]:
        try:
            n = int(arg.strip())
        except ValueError:
            print(f"expected an integer index, got {arg!r}")
            return None
        if n < 1 or n > len(self.hits):
            print(f"index out of range; have {len(self.hits)} sorrys")
            return None
        return n

    def _chat(self, question: str) -> None:
        question = question.strip()
        if not question:
            print("usage: chat QUESTION")
            return
        print("[agent] asking vLLM about the project...")
        try:
            answer = ask_project_question(
                question,
                project_context=self.project_context,
                extra_instructions=self.session_instructions,
            )
        except Exception as e:
            print(f"[agent] vLLM call failed: {e}")
            print(f"[agent] endpoint = {resolved_base_url()}")
            print("[agent] local context is still available with `context`.")
            return
        print(answer)

    # -- commands ----------------------------------------------------------

    def do_list(self, arg: str) -> None:
        """list  —  scan the project for sorrys via Lean LSP (~30s warmup first time)."""
        print(f"[agent] scanning {self.project_root} via Lean LSP...")
        try:
            self.hits = find_sorrys(self.project_root)
        except FileNotFoundError as e:
            print(f"[agent] {e}; is `lake` on PATH and the project usable?")
            return
        if not self.hits:
            print("(no sorrys found)")
            return
        w = len(str(len(self.hits)))
        for i, h in enumerate(self.hits, 1):
            rel = os.path.relpath(h.file, self.project_root)
            print(f"  {i:>{w}}  {rel}:{h.line}  {h.decl_name}")

    def do_show(self, arg: str) -> None:
        """show N  —  print the declaration containing sorry #N, with surrounding context."""
        if self._need_hits(): return
        n = self._idx(arg);
        if n is None: return
        h = self.hits[n - 1]
        rel = os.path.relpath(h.file, self.project_root)
        print(f"--- {rel}  (lines {h.decl_range[0]}-{h.decl_range[1]}, decl: {h.decl_name}) ---")
        if h.imports:
            print("--- imports ---")
            print(h.imports)
            print("--- context ---")
        print(h.surrounding)
        if h.diagnostic_message:
            print("--- diagnostic ---")
            print(h.diagnostic_message)

    def do_ask(self, arg: str) -> None:
        """ask N  —  send sorry #N to vLLM and print the candidate proof (does not splice)."""
        if self._need_hits(): return
        n = self._idx(arg)
        if n is None: return
        h = self.hits[n - 1]
        print(f"[agent] asking vLLM about #{n} {h.decl_name}...")
        try:
            p = ask_for_proof(
                h.decl_name,
                h.signature,
                h.surrounding,
                project_context=self.project_context,
                imports=h.imports,
                diagnostic_message=h.diagnostic_message,
                extra_instructions=self.session_instructions,
            )
        except Exception as e:
            print(f"[agent] vLLM call failed: {e}")
            print("[agent] is vllm-up still running? OPENAI_BASE_URL =", os.environ.get("OPENAI_BASE_URL", "(unset)"))
            return
        self.proposals[n] = p
        print(f"[agent] {p.completion_tokens} tokens; model={p.model}")
        print("--- candidate ---")
        print(p.proof)
        print("--- (use `try N` to apply + lake build) ---")

    def do_try(self, arg: str) -> None:
        """try N  —  splice the last candidate for #N, lake build the file; revert on failure."""
        if self._need_hits(): return
        n = self._idx(arg)
        if n is None: return
        if n not in self.proposals:
            print(f"no candidate for #{n} yet; run `ask {n}` first")
            return
        h = self.hits[n - 1]
        p = self.proposals[n]
        target = Path(h.file)
        snapshot = _snapshot(target)
        try:
            patched = splice(target.read_text(encoding="utf-8"), h, p.proof)
            target.write_text(patched, encoding="utf-8")
            module = _module_name_for(self.project_root, target)
            print(f"[agent] lake build {module or '(full project)'}...")
            rc, out, err = lake_build(self.project_root, module)
            if rc == 0:
                print("[agent] OK — leaving change in place.")
            else:
                shutil.copy2(snapshot, target)
                print(f"[agent] BUILD FAILED (rc={rc}); reverted {target.name}.")
                tail = (err.strip() or out.strip()).splitlines()[-20:]
                for line in tail: print("  | " + line)
        finally:
            shutil.rmtree(snapshot.parent, ignore_errors=True)

    def do_build(self, arg: str) -> None:
        """build [MODULE]  —  run `lake build` (whole project, or a specific module)."""
        module = arg.strip() or None
        print(f"[agent] lake build {module or '(full project)'}...")
        rc, out, err = lake_build(self.project_root, module)
        sys.stdout.write(out)
        sys.stderr.write(err)
        print(f"[agent] exit={rc}")

    def do_chat(self, arg: str) -> None:
        """chat QUESTION  —  ask vLLM a free-form question about the project."""
        self._chat(arg)

    def do_q(self, arg: str) -> None:
        """q QUESTION  —  short alias for `chat QUESTION`."""
        self._chat(arg)

    def do_context(self, arg: str) -> None:
        """context  —  print the project context that will be sent to vLLM."""
        include_readme = arg.strip() != "--no-readme"
        print(render_project_context(
            self.project_context,
            extra_instructions=self.session_instructions,
            include_readme=include_readme,
        ))

    def do_refresh_context(self, arg: str) -> None:
        """refresh_context  —  rescan Lake/project metadata and instruction files."""
        print(f"[agent] refreshing context for {self.project_root}...")
        self.project_context = inspect_project(
            self.project_root,
            instructions_path=self.instructions_path,
        )
        print("[agent] context refreshed.")

    def do_instructions(self, arg: str) -> None:
        """instructions [TEXT|@PATH|clear]  —  show/add per-session guidance."""
        raw = arg.strip()
        if not raw:
            if self.project_context.instructions:
                print("--- project instructions ---")
                print(self.project_context.instructions)
            if self.session_instructions:
                print("--- session instructions ---")
                print(self.session_instructions)
            if not self.project_context.instructions and not self.session_instructions:
                print("(no instructions loaded)")
            return
        if raw == "clear":
            self.session_instructions = ""
            print("[agent] session instructions cleared.")
            return
        if raw.startswith("@"):
            path = Path(raw[1:]).expanduser()
            if not path.is_absolute():
                path = self.project_root / path
            text = _read_text_limited(path, max_chars=8000)
            if not text:
                print(f"[agent] no readable instruction text at {path}")
                return
            addition = f"# {path.name}\n{text}"
        else:
            addition = raw
        self.session_instructions = (
            self.session_instructions + "\n\n" + addition
        ).strip()
        print("[agent] session instructions updated.")

    def do_env(self, arg: str) -> None:
        """env  —  print the env vars we care about."""
        print(f"  LEAN_REPO_PATH={os.environ.get('LEAN_REPO_PATH', '(unset)')}")
        print(f"  OPENAI_BASE_URL={_env_label('OPENAI_BASE_URL', DEFAULT_BASE_URL)}")
        print(f"  OPENAI_API_KEY={'set' if os.environ.get('OPENAI_API_KEY') else DEFAULT_API_KEY + ' (default)'}")
        print(f"  VLLM_MODEL={_env_label('VLLM_MODEL', DEFAULT_MODEL)}")
        print(f"  project={self.project_root}")
        if self.project_context.instruction_files:
            print("  instruction_files=" + ", ".join(self.project_context.instruction_files))
        else:
            print("  instruction_files=(none)")

    def do_quit(self, arg: str) -> bool:
        """quit / exit  —  leave the REPL."""
        return True
    do_exit = do_quit
    do_EOF = do_quit

    def default(self, line: str) -> None:
        if line.strip():
            self._chat(line)
            return
        print("type `help` for the command list, or type a project question.")


# ---------------------------------------------------------------------------
#  Entrypoint
# ---------------------------------------------------------------------------

def _locate_dotenv(start: Path) -> Optional[Path]:
    """Walk upward from `start` looking for a `.env` (or `agent/.env`)."""
    cur = start.resolve()
    for _ in range(8):
        for cand in (cur / ".env", cur / "agent" / ".env"):
            if cand.is_file():
                return cand
        if cur == cur.parent: break
        cur = cur.parent
    return None


def run_loop(
    project_root: Path,
    *,
    instructions_path: Optional[Path] = None,
    session_instructions: str = "",
) -> int:
    project_context = inspect_project(project_root, instructions_path=instructions_path)
    intro_lines = [
        "",
        "  gcd-agent  —  slash-command REPL over a Lean project + vLLM",
        f"  project    : {project_root}",
        f"  package    : {project_context.package_name or '(unknown)'}",
        f"  toolchain  : {project_context.toolchain or '(unknown)'}",
        f"  source     : {', '.join(project_context.source_roots) or '(none detected)'}",
        f"  sorry/admit: {project_context.sorry_like_count}",
        f"  endpoint   : {_env_label('OPENAI_BASE_URL', DEFAULT_BASE_URL)}",
        f"  model      : {_env_label('VLLM_MODEL', DEFAULT_MODEL)}",
        "",
        "  commands   : context, chat QUESTION, instructions, list, show N, ask N,",
        "               try N, build [MODULE], env, quit",
        "               (you can also just type a project question)",
        "               (type `help <cmd>` for details)",
        "",
    ]
    shell = AgentShell(
        project_root,
        project_context=project_context,
        instructions_path=instructions_path,
        session_instructions=session_instructions,
    )
    shell.intro = "\n".join(intro_lines)
    try:
        shell.cmdloop()
    except KeyboardInterrupt:
        print()
        return 130
    return 0


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(prog="gcd-agent",
        description="Slash-command REPL over a Lean project + vLLM endpoint.")
    ap.add_argument("--project", type=Path, default=None,
        help="Path to the Lean project root. Defaults to $LEAN_REPO_PATH "
             "(loaded from .env if needed).")
    ap.add_argument("--env-file", type=Path, default=None,
        help="Explicit path to a .env file; otherwise search cwd and upward.")
    ap.add_argument("--instructions", type=Path, default=None,
        help="Path to a project instruction file. Defaults to .gcd/agent.md, "
             ".gcd/context.md, .gcd/instructions.md, or AGENTS.md if present.")
    ap.add_argument("--context", action="append", default=[],
        help="Inline session instruction to include in every vLLM prompt. "
             "May be passed more than once.")
    args = ap.parse_args(argv)

    env_path = args.env_file or _locate_dotenv(Path.cwd())
    if env_path:
        load_env_file(env_path)

    if args.project is not None:
        project = args.project
    elif "LEAN_REPO_PATH" in os.environ:
        project = Path(os.environ["LEAN_REPO_PATH"])
    else:
        sys.stderr.write(
            "gcd-agent: no Lean project path.\n"
            "  Set LEAN_REPO_PATH in your shell, put it in a .env file next\n"
            "  to the agent (see agent/.env.example), or pass --project PATH.\n"
        )
        return 2

    project = project.expanduser().resolve()
    if not (project / "lakefile.lean").is_file() and not (project / "lakefile.toml").is_file():
        sys.stderr.write(f"gcd-agent: {project} has no lakefile.lean / lakefile.toml\n")
        return 2

    env_instructions = os.environ.get("LEAN_AGENT_CONTEXT", "").strip()
    session_instructions = "\n\n".join(
        part for part in [env_instructions, *args.context]
        if part and part.strip()
    )
    instructions_path = args.instructions
    if instructions_path is None and os.environ.get("LEAN_AGENT_INSTRUCTIONS"):
        instructions_path = Path(os.environ["LEAN_AGENT_INSTRUCTIONS"])

    return run_loop(
        project,
        instructions_path=instructions_path,
        session_instructions=session_instructions,
    )


if __name__ == "__main__":
    raise SystemExit(main())
