"""Utilities for managing SLURM jobs, SSH connections, and port forwarding on HPC clusters."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['find_free_port', 'start_or_connect', 'job_stat', 'get_port_forwarding_command', 'update_ssh_node_config']

# %% ../nbs/00_core.ipynb 4
import socket


# %% ../nbs/00_core.ipynb 5
def find_free_port(above=8000):
    "Find a free port above `above`"
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(('', 0))
        port = s.getsockname()[1]
        while port <= above:
            s.close()
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.bind(('', 0))
            port = s.getsockname()[1]
        return port

# %% ../nbs/00_core.ipynb 7
import subprocess


# %% ../nbs/00_core.ipynb 8
def start_or_connect(job_name, host,
                     slurm_args="--qos=debug --gpus=1 --cpus-per-task=8 --mem=200G --time=01:00:00", return_cmd=False):
    """SSH to host, start a tmux session, and allocate a SLURM job inside it.

    Checks (via ssh+squeue) whether a SLURM job named `job_name` is already running.
    - If running: reattaches to the existing tmux session on the login node.
    - If not running: creates a tmux session that runs `salloc` to allocate resources.

    params:
        job_name: name for both the SLURM job and tmux session
        host: SSH host alias for the login node (must be in ~/.ssh/config)
        slurm_args: arguments passed to salloc (resources, time, qos, etc.)
        return_cmd: if True, return the command string; otherwise just print it
    """
    # Check if job is already running
    check = subprocess.run(
        ["ssh", host, f"squeue --me --name={job_name} --states=RUNNING --noheader"],
        capture_output=True, text=True
    )
    job_running = bool(check.stdout.strip())
    
    salloc_cmd = f"salloc --job-name={job_name} {slurm_args}"

    if job_running:
        print(f"Job '{job_name}' is already running. Reattaching to tmux...")
        ssh_cmd = f"ssh -t {host} \"tmux new-session -A -s {job_name}\""
    else:
        print(f"No running job '{job_name}' found. Starting salloc...")
        ssh_cmd = f"ssh -t {host} \"tmux new-session -A -s {job_name} '{salloc_cmd}'\""


    if return_cmd:
        return ssh_cmd
    else:
        print(f"Run this in your terminal:\n{ssh_cmd}")
        return

# %% ../nbs/00_core.ipynb 11
def job_stat(job_name, host,silent=False):
    """Get status info for a running SLURM job and print helpful commands.

    SSHs to `host` and queries squeue for the job's ID and node.
    Prints helper commands for getting a terminal, cancelling the job, etc.

    params:
        job_name: name of the SLURM job
        host: SSH host alias for the login node
    returns:
        dict with 'job_id' and 'node' keys, or None if no job found
    """
    result = subprocess.run(
        ["ssh", host,
         f"squeue --me --name={job_name} --states=RUNNING --Format=JobID,NodeList,TimeLeft,Partition --noheader"],
        capture_output=True, text=True
    )
    output = result.stdout.strip()
    if not output:
        if not silent:
            print(f"No running job '{job_name}' found on {host}.")
        return None

    parts = output.split()
    job_id = parts[0]
    node = parts[1]
    time_left = parts[2] if len(parts) > 2 else "?"
    partition = parts[3] if len(parts) > 3 else "?"

    if not silent:
        print(f"Job '{job_name}' status on {host}:")
        print(f"  Job ID:    {job_id}")
        print(f"  Node:      {node}")
        print(f"  Time left: {time_left}")
        print(f"  Partition: {partition}")
        print()
        print("Useful commands (run these on the login node or via ssh):")
        print(f"  # Get a shell on the compute node:")
        print(f"  ssh -t {host} 'srun --jobid={job_id} --overlap --pty bash'")
        print(f"  # Cancel the job:")
        print(f"  ssh {host} 'scancel {job_id}'")
        print(f"  # View job details:")
        print(f"  ssh {host} 'scontrol show job {job_id}'")

    return node, job_id

# %% ../nbs/00_core.ipynb 13
def get_port_forwarding_command(local_port, remote_port, host, node, local_network="hyak.local"):
    """Get the command to forward local_port to remote_port on a compute node via the login host.
    Uses SSH local port forwarding with a ProxyJump through the login node.
    This function would not run the actual command, just print it to screen.
    """
    cmd = (
        f"ssh -N -f "
        f"-L {local_port}:{node}.{local_network}:{remote_port} "
        f"{host}"
    )
    print(cmd)
    return cmd

# %% ../nbs/00_core.ipynb 15
import re
from pathlib import Path


# %% ../nbs/00_core.ipynb 16
def update_ssh_node_config(job_name, host, config_path=None):
    """Query the SLURM node running `job_name` and update the SSH node config with its hostname.

    SSHs to `host` (login node) to find which compute node is running the job,
    then rewrites the `Hostname` line in the SSH sub-config file so that
    VSCode (or plain ssh) can ProxyJump directly to the compute node.

    params:
        job_name: name of the running SLURM job
        host: SSH host alias for the login node (e.g. 'klone-login')
        config_path: path to the SSH node config file. If None, defaults to
                     ~/.ssh/{cluster}-node-config where cluster is derived
                     from host (e.g. 'klone-login' → 'klone').
    returns:
        the node hostname string
    """
    # Get the node name 
    node,_ = job_stat(job_name, host,silent=True)
    if not node:
        raise RuntimeError(f"No running SLURM job named '{job_name}' found on {host}")

    # Determine config file path
    if config_path is None:
        cluster = host.replace("-login", "")
        config_path = Path.home() / ".ssh" / f"{cluster}-node-config"
    else:
        config_path = Path(config_path)

    # Read and update the Hostname line
    content = config_path.read_text()
    new_content = re.sub(r"(Hostname)\s+\S+", f"\\1 {node}", content)
    config_path.write_text(new_content)

    print(f"Updated {config_path}: Hostname → {node}")
    return node
