"""Utilities for managing SLURM jobs, SSH connections, and port forwarding on HPC clusters."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['find_free_port', 'start_or_connect', 'get_job_node', 'get_port_forwarding_command']

# %% ../nbs/00_core.ipynb 4
import socket

def find_free_port(above=8000):
    "Find a free port above `above`"
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(('', 0))
        port = s.getsockname()[1]
        while port <= above:
            s.close()
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            s.bind(('', 0))
            port = s.getsockname()[1]
        return port

# %% ../nbs/00_core.ipynb 6
import subprocess

def start_or_connect(job_name, host, command=None,
                     slurm_args="--qos=debug --gpus=1 --cpus-per-task=8 --mem=200G --time=01:00:00"):
    """SSH to host and manage a SLURM job with nested tmux sessions.

    Checks (via ssh+squeue) whether a SLURM job named `job_name` is already running.
    - If running: reattaches to the existing outer tmux session on the login node.
    - If not running: creates an outer tmux on the login node that runs
      `salloc` to get a compute node, then starts an inner tmux on the compute
      node via `srun --pty`. Optionally runs `command` inside the inner tmux.

    params:
        job_name: name for both the SLURM job and tmux sessions
        host: SSH host alias for the login node (must be in ~/.ssh/config)
        command: optional command to run in the inner tmux's initial window
        slurm_args: arguments passed to salloc (resources, time, qos, etc.)
    """
    # Check if job is already running
    check = subprocess.run(
        ["ssh", host, f"squeue --me --name={job_name} --states=RUNNING --noheader"],
        capture_output=True, text=True
    )
    job_running = bool(check.stdout.strip())

    if job_running:
        print(f"Job '{job_name}' is already running. Reattaching to outer tmux...")
        ssh_cmd = f'ssh -t {host} "tmux new-session -A -s {job_name}"'
    else:
        print(f"No running job '{job_name}' found. Starting salloc + inner tmux...")
        # Inner tmux runs on compute node via srun
        inner_tmux = f"tmux new-session -s {job_name}"
        if command:
            # Run command in the inner tmux window, then exec bash so the window stays alive
            inner_tmux += f" \\\"{command}; exec bash\\\""

        salloc_cmd = f"salloc --job-name={job_name} {slurm_args} srun --pty {inner_tmux}"
        # Outer tmux on login node runs salloc as its shell command
        ssh_cmd = f"ssh -t {host} \"tmux new-session -A -s {job_name} '{salloc_cmd}'\""

    print(ssh_cmd)
    return ssh_cmd

# %% ../nbs/00_core.ipynb 8
def get_job_node(job_name, host):
    """Get the node that is running the job with name `job_name` on host `host`.
    Prints and returns the ssh command that queries squeue for the node.
    """
    squeue_cmd = (
        f"squeue --me --name={job_name} --states=RUNNING "
        f"--Format=NodeList --noheader"
    )
    ssh_cmd = f"ssh {host} '{squeue_cmd}'"
    print(ssh_cmd)
    return ssh_cmd

# %% ../nbs/00_core.ipynb 10
def get_port_forwarding_command(local_port, remote_port, host, node, local_network="hyak.local"):
    """Get the command to forward local_port to remote_port on a compute node via the login host.
    Uses SSH local port forwarding with a ProxyJump through the login node.
    This function would not run the actual command, just print it to screen.
    """
    cmd = (
        f"ssh -N -f "
        f"-L {local_port}:{node}.{local_network}:{remote_port} "
        f"{host}"
    )
    print(cmd)
    return cmd
