"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['find_free_port', 'start_or_connect']

# %% ../nbs/00_core.ipynb 4
def find_free_port(above=8000):
    "Find a free port above `above`"
    pass

# %% ../nbs/00_core.ipynb 5
def start_or_connect(job_name,host):
    """print command to ssh to host and start tmux session with job_name if it doesn't exist, otherwise connect to it
    When starting a new job, make sure to start the tmux session with the same name as the job name.
    When connecting to an existing job, make sure to connect to the tmux session with the same name that is running it.

    This function would not run the actual command, just print it to screen

    params:
        job_name: name of the slurm job to connect to or start
        host: the ssh host alist to connect to, must be present in ~/.ssh/config and previously authenticated.
    """
    pass
