"""vLLM extension: bring up an OpenAI-compatible endpoint on a SLURM compute node, exposed to the laptop."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_vllm.ipynb.

# %% auto 0
__all__ = ['DEFAULT_SLURM_ARGS', 'DEFAULT_MODEL', 'sif_exists', 'build_sif', 'wait_for_discovery', 'vllm_up', 'vllm_down']

# %% ../nbs/02_vllm.ipynb 4
import json
import shlex
import subprocess
import time
from pathlib import Path

from .core import (
    start_or_connect,
    job_stat,
    get_port_forwarding_command,
    update_ssh_node_config,
)

# %% ../nbs/02_vllm.ipynb 5
DEFAULT_SLURM_ARGS = (
    "--account=amath --partition=gpu-l40s --gres=gpu:1 "
    "--cpus-per-task=8 --mem=48G --time=04:00:00"
)
DEFAULT_MODEL = "Qwen/Qwen3-8B"

# %% ../nbs/02_vllm.ipynb 7
def sif_exists(host, sif_path="/mmfs1/gscratch/scrubbed/$USER/vllm.sif"):
    "True iff the apptainer image is on `host`."
    r = subprocess.run(
        ["ssh", host, f"[ -f {sif_path} ] && echo yes || echo no"],
        capture_output=True, text=True,
    )
    return r.stdout.strip() == "yes"

# %% ../nbs/02_vllm.ipynb 9
def build_sif(host, remote_vllm_dir="projects/gcd/slurm-ops/vllm", silent=False):
    """Submit ~/<remote_vllm_dir>/build-sif.job on `host` and block until done.

    Returns the slurm exit code (0 = sif built). The first build pulls a ~10GB
    docker image and takes ~25-35 min; subsequent calls are no-ops because of
    sif_exists().
    """
    if not silent:
        print(f"[vllm] submitting build-sif.job on {host} (~25-35 min first time)...")
    sub = subprocess.run(
        ["ssh", host, f"cd ~/{remote_vllm_dir} && sbatch --parsable build-sif.job"],
        capture_output=True, text=True, check=True,
    )
    jobid = sub.stdout.strip()
    if not jobid:
        raise RuntimeError(f"sbatch returned no job id; stderr:\n{sub.stderr}")
    if not silent:
        print(f"[vllm] SIF build job: {jobid}; tailing slurm-{jobid}.out (Ctrl-C only stops the tail)")
    # Tail until the job leaves the queue, then return its exit code.
    tail_script = (
        f"log=~/{remote_vllm_dir}/slurm-{jobid}.out; "
        f"for _ in $(seq 1 600); do [ -f \"$log\" ] && break; sleep 2; done; "
        f"( tail -n +1 -f \"$log\" ) & tp=$!; "
        f"while squeue -h -j {jobid} 2>/dev/null | grep -q .; do sleep 5; done; "
        f"sleep 2; kill $tp 2>/dev/null || true; wait $tp 2>/dev/null || true; "
        f"ec=$(sacct -j {jobid}.batch -o ExitCode -P -n 2>/dev/null | head -1 | cut -d: -f1); "
        f"exit ${{ec:-0}}"
    )
    r = subprocess.run(["ssh", host, tail_script])
    return r.returncode

# %% ../nbs/02_vllm.ipynb 11
def wait_for_discovery(job_name, host, timeout_s=1800, poll_s=5, silent=False):
    """Block until ~/.vllm-discovery/<job_name>.json exists on `host`.

    Returns the parsed JSON dict ({"node": ..., "port": ..., "model": ...}).
    Bails early if the SLURM job leaves the queue before the file appears.
    """
    disc_path = f"$HOME/.vllm-discovery/{job_name}.json"
    deadline = time.time() + timeout_s
    if not silent:
        print(f"[vllm] waiting for {disc_path} on {host} (up to {timeout_s//60} min)...")
    while time.time() < deadline:
        r = subprocess.run(
            ["ssh", host, f"cat {disc_path} 2>/dev/null || true"],
            capture_output=True, text=True,
        )
        if r.stdout.strip():
            return json.loads(r.stdout)
        # If the job is no longer pending/running, fail fast.
        if job_stat(job_name, host, silent=True) is None:
            log = subprocess.run(
                ["ssh", host, f"tail -40 $HOME/.vllm-discovery/{job_name}.log 2>/dev/null"],
                capture_output=True, text=True,
            ).stdout
            raise RuntimeError(
                f"job '{job_name}' is no longer in the queue and no discovery file appeared.\n"
                f"Recent serve log:\n{log}"
            )
        time.sleep(poll_s)
    raise TimeoutError(f"timed out waiting for {disc_path}")

# %% ../nbs/02_vllm.ipynb 13
def vllm_up(
    job_name,
    host,
    model=DEFAULT_MODEL,
    slurm_args=DEFAULT_SLURM_ARGS,
    local_port=8000,
    remote_vllm_dir="projects/gcd/slurm-ops/vllm",
    update_node_config=True,
):
    """Bring up a vLLM OpenAI-compatible endpoint on `host` and forward it to localhost.

    Wires together the upstream slurm-ops primitives:
      - `start_or_connect` (re-uses or starts the tmux+salloc session)
      - `job_stat`          (resolves the compute node after allocation)
      - `get_port_forwarding_command` (composes the ssh -L command)
      - `update_ssh_node_config`      (rewrites ~/.ssh/<cluster>-node-config so
                                       VSCode can attach to the compute node)

    The only material change vs upstream's pattern is that we *execute* the
    commands those functions return, and the salloc body ends in `srun --pty
    ~/<remote_vllm_dir>/serve.sh` (which runs `apptainer exec --nv vllm.sif
    python3 -m vllm.entrypoints.openai.api_server`) rather than a bare shell.

    Args:
        job_name: shared name for SLURM job, tmux session, discovery file.
        host: ssh alias for the login node (e.g. 'klone-login').
        model: HF model id served by vLLM. Default Qwen/Qwen3-8B.
        slurm_args: salloc flags (account/partition/gres/mem/time).
        local_port: local port to bind the forwarded endpoint. Default 8000,
                    so OPENAI_BASE_URL stays stable across invocations.
        remote_vllm_dir: path of vllm/ on `host` (relative to $HOME).
        update_node_config: if True, rewrite ~/.ssh/<cluster>-node-config so
                            you can `ssh <cluster>-node` (and VSCode) directly
                            to the compute node.

    Returns dict with `base_url`, `model`, `node`, `local_port`, `remote_port`.
    """
    # 1. SIF must exist on the cluster.
    if not sif_exists(host):
        rc = build_sif(host, remote_vllm_dir=remote_vllm_dir)
        if rc != 0 or not sif_exists(host):
            raise RuntimeError(f"SIF build failed (exit {rc}); see slurm-*.out in ~/{remote_vllm_dir}/")

    # 2. The salloc body — append our serve.sh after the slurm flags.
    serve_cmd = f"srun --pty ~/{remote_vllm_dir}/serve.sh"
    full_slurm_args = f"{slurm_args} {serve_cmd}"

    # 3. Reuse upstream's start_or_connect — but *run* the ssh command instead
    #    of having the user paste it. We pass MODEL via SSH command line, since
    #    serve.sh honors $MODEL.
    ssh_cmd = start_or_connect(job_name, host, slurm_args=full_slurm_args, return_cmd=True)

    # The returned cmd is the upstream-canonical
    #   ssh -t <host> "tmux new-session -A -s <name> 'salloc ... serve.sh'"
    # We want MODEL set on the remote side. Easiest: wrap the existing tmux body.
    if model != DEFAULT_MODEL:
        ssh_cmd = ssh_cmd.replace(
            "tmux new-session -A -s",
            f"MODEL={shlex.quote(model)} tmux new-session -A -s",
            1,
        )

    # Execute under -d so the tmux session detaches immediately. We rewrite -A
    # to -A -d so the user's terminal isn't taken over (their original is for
    # interactive notebook usage where attaching is desired).
    ssh_cmd_detached = ssh_cmd.replace("tmux new-session -A", "tmux new-session -A -d", 1)
    print(f"[vllm] launching: {ssh_cmd_detached}")
    subprocess.run(ssh_cmd_detached, shell=True, check=True)

    # 4. Wait until salloc allocates (job_stat returns a node).
    print(f"[vllm] waiting for salloc to allocate a GPU node...")
    for _ in range(360):  # 30 min cap on queue wait
        info = job_stat(job_name, host, silent=True)
        if info is not None:
            node, jobid = info
            print(f"[vllm] allocated: job {jobid} on {node}")
            break
        time.sleep(5)
    else:
        raise TimeoutError(f"salloc never reached RUNNING state for '{job_name}'")

    # 5. Wait for vLLM itself to be ready (discovery file written by serve.sh).
    disc = wait_for_discovery(job_name, host)
    node = disc["node"]
    remote_port = disc["port"]

    # 6. Open the local forward. We compose with upstream's helper, then run it.
    fwd_cmd = get_port_forwarding_command(local_port, remote_port, host, node)
    # `ssh -N -f -L …` would fork; we use `ssh -O forward` against the existing
    # ControlMaster, which is the same idea but doesn't leak a process. Both
    # forms are equivalent in effect; we use the latter to match how upstream's
    # interactive notebook user would manage forwards across re-runs.
    of_cmd = f"ssh -O forward -L {local_port}:{node}.hyak.local:{remote_port} {host}"
    print(f"[vllm] opening forward: {of_cmd}")
    subprocess.run(of_cmd, shell=True, check=True)

    # 7. Optionally update the ssh node config so VSCode can attach to the compute node.
    if update_node_config:
        try:
            update_ssh_node_config(job_name, host)
        except (RuntimeError, FileNotFoundError) as e:
            print(f"[vllm] (skipped update_ssh_node_config: {e})")

    base_url = f"http://localhost:{local_port}/v1"
    print()
    print("=" * 60)
    print(f"  vLLM ready: {disc['model']} on {node}:{remote_port}")
    print(f"  base_url = {base_url}")
    print(f"  export OPENAI_BASE_URL={base_url!r}")
    print(f"  export OPENAI_API_KEY='dummy'")
    print(f"  export VLLM_MODEL={disc['served_name']!r}")
    print(f"  attach: ssh {host} -t tmux attach -t {job_name}")
    print(f"  log:    ssh {host} tail -f ~/.vllm-discovery/{job_name}.log")
    print("=" * 60)
    return {
        "base_url": base_url,
        "model": disc["model"],
        "served_name": disc["served_name"],
        "node": node,
        "local_port": local_port,
        "remote_port": remote_port,
        "job_name": job_name,
        "host": host,
    }

# %% ../nbs/02_vllm.ipynb 15
def vllm_down(job_name, host, local_port=8000, remote_port=None, node=None):
    """Tear down a vllm_up-style session.

    Cancels the slurm job, kills the tmux session, and cancels the local
    forward. Idempotent — safe to run if any piece is already gone.

    If `remote_port` / `node` are None, attempts to recover them from
    ~/.vllm-discovery/<job_name>.json on `host` so the `ssh -O cancel` matches.
    """
    info = job_stat(job_name, host, silent=True)

    # Try to recover node + remote_port from the discovery file if not given.
    if (node is None or remote_port is None):
        r = subprocess.run(
            ["ssh", host, f"cat $HOME/.vllm-discovery/{job_name}.json 2>/dev/null || true"],
            capture_output=True, text=True,
        )
        if r.stdout.strip():
            d = json.loads(r.stdout)
            node = node or d.get("node")
            remote_port = remote_port or d.get("port")

    # 1. cancel local forward (best-effort).
    if node and remote_port:
        cancel = f"ssh -O cancel -L {local_port}:{node}.hyak.local:{remote_port} {host}"
        print(f"[vllm] {cancel}")
        subprocess.run(cancel, shell=True)
    else:
        print("[vllm] (no node/remote_port known; skipping local forward cancel)")

    # 2. scancel.
    if info is not None:
        _, jobid = info
        print(f"[vllm] scancel {jobid}")
        subprocess.run(["ssh", host, f"scancel {jobid}"])
    else:
        print(f"[vllm] no '{job_name}' job in queue")

    # 3. tmux kill (in case it lingers).
    subprocess.run(["ssh", host, f"tmux kill-session -t {job_name} 2>/dev/null || true"])
    print("[vllm] done.")
