"""Export nbs/02_vllm.ipynb to slurm_ops/vllm.py.

This intentionally exports only the vLLM notebook. A global nbdev export would
also inspect unrelated notebooks in this repo.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
NB_PATH = ROOT / "nbs" / "02_vllm.ipynb"
OUT_PATH = ROOT / "slurm_ops" / "vllm.py"

EXPORTS = [
    "DEFAULT_ACCOUNT",
    "DEFAULT_PARTITION",
    "DEFAULT_GRES",
    "DEFAULT_CPUS_PER_TASK",
    "DEFAULT_MEM",
    "DEFAULT_TIME",
    "DEFAULT_SLURM_ARGS",
    "DEFAULT_MODEL",
    "SHARED_SIF_PATH",
    "make_slurm_args",
    "sif_exists",
    "resolve_sif",
    "build_sif",
    "wait_for_discovery",
    "local_port_available",
    "choose_local_port",
    "open_ssh_forward",
    "close_ssh_forward",
    "vllm_up",
    "vllm_down",
    "vllm_chat",
    "main_up",
    "main_down",
    "main_chat",
]


def cell_source(cell: dict) -> str:
    source = cell.get("source", "")
    return "".join(source) if isinstance(source, list) else source


def main() -> int:
    nb = json.loads(NB_PATH.read_text(encoding="utf-8"))
    parts = [
        '"""vLLM extension: bring up an OpenAI-compatible endpoint on Klone/HYAK and expose it locally."""\n',
        "\n# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_vllm.ipynb.\n\n",
        "# %% auto 0\n",
        f"__all__ = {EXPORTS!r}\n\n",
    ]

    for index, cell in enumerate(nb.get("cells", [])):
        if cell.get("cell_type") != "code":
            continue
        source = cell_source(cell)
        lines = source.splitlines()
        if not lines or lines[0].strip() != "#| export":
            continue
        code = "\n".join(lines[1:]).rstrip()
        if not code:
            continue
        parts.append(f"# %% ../nbs/02_vllm.ipynb {index}\n")
        parts.append(code + "\n\n")

    OUT_PATH.write_text("".join(parts).rstrip() + "\n", encoding="utf-8")
    print(f"exported {NB_PATH.relative_to(ROOT)} -> {OUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
