# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_uv',
                'doc_host': 'https://JohnDoe.github.io',
                'git_url': 'https://github.com/JohnDoe/nbdev_uv',
                'lib_path': 'nbdev_uv'},
  'syms': {'nbdev_uv.core': {'nbdev_uv.core.foo': ('core.html#foo', 'nbdev_uv/core.py')}}}
